### ISSUE TITLE
Cannot reproduce example

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/pyxenon#31]
I have the following script that is a copy paste of the [example](http://pyxenon.readthedocs.io/en/latest/quick-start.html):
```python
from xenon import (FileSystem, JobDescription, PasswordCredential, Path, Scheduler)
import xenon

xenon.init()

credential = PasswordCredential(
    username='xenon',
    password='javagat')

remotefs = FileSystem.create(
    'sftp', location='localhost:10022',
    password_credential=credential)

target = Path('hello.sh')

if remotefs.exists(target):
    remotefs.delete(target)

remotefs.write_to_file(
    target,
    [b'#!/bin/sh\n',
     b'echo "Hello, World!"\n'])

scheduler = Scheduler.create(
    adaptor='slurm',
    location='localhost:10022',
    password_credential=credential)
........
```

When I run the previous script it crashes with the following error:
```bash
18:19:28 $ python test_xenon.py 
Traceback (most recent call last):
  File "test_xenon.py", line 29, in <module>
    password_credential=credential)
  File "/home/felipe/miniconda3/envs/mdstudio3/lib/python3.6/site-packages/xenon/oop.py", line 304, in static_method
    grpc_call(cls.__stub__(__server__), m, request))
  File "/home/felipe/miniconda3/envs/mdstudio3/lib/python3.6/site-packages/xenon/oop.py", line 271, in grpc_call
    raise make_exception(method, e) from None
xenon.exceptions.InvalidLocationException: Xenon (StatusCode.FAILED_PRECONDITION): "nl.esciencecenter.xenon.InvalidLocationException: slurm adaptor: Invalid location: localhost:10022" in create
```
Inside the Container a `hello.sh` was successfully created and  the port  `10022` is open:
```bash
18:21:15 $ nmap -p 10022 localhost
Host is up (0.00015s latency).
PORT      STATE SERVICE
10022/tcp open  unknown
```

**Comment by jhidding** [comment]
Thanks for reporting this, the address should be "ssh://localhost:10022"

**Comment by felipeZ** [comment]
I made a pull request
